name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Build driver
        run: |
          npm run format:check
          npm run build

      - name: Generate changelog
        run: |
          mkdir .bin
          node_modules/.bin/conventional-changelog -p angular -r 1 -o .bin/DRAFT.md
          cat .bin/DRAFT.md

      - name: Create driver release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./.bin/DRAFT.md
          draft: true
          prerelease: false

      - name: Upload release SVG asset
        id: upload-release-asset-svg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/cloudsigma.svg
          asset_name: cloudsigma.svg
          asset_content_type: image/svg+xml

      - name: Upload release CSS asset
        id: upload-release-asset-css
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/component.css
          asset_name: component.css
          asset_content_type: text/css

      - name: Upload release JS asset
        id: upload-release-asset-js
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/component.js
          asset_name: component.js
          asset_content_type: application/javascript
